name: e2e

on: [push]

jobs:
  test:
    if: github.event.deployment_status.state == 'success'
    name: Smoke tests
    runs-on: ubuntu-latest
    env:
      DEPLOY_URL: ${{ github.event.deployment_status.target_url }}
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          ls -la
